language: node_js
node_js: node
services: 
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: hU2sv953dQo+fGlq23GTOVZA81ZVqqDZxDOV9dAJuBUV/9/N3qpFB1ZcEDjA1ZDH6oXipfzPhatnkevMZOiM4RkgOZB366ohpYDlGmizWMzFgz4lsTEyCt5oXVm6Zl8HLId3p967ocAS8oauWGRNm9D10JR011FCI2Yho5gPoyMaZgtJmgVdjUPA+v1FX9pFQLwV+Bbl+w68vvBy107MGvIgCCCiIdF8X0GRvMfVUgVHEjf8W9Nc9VSyhkLrWISB0eQqK4L1m3yCqiZN7CDjjXr9C1HVAyMNGzVLwkUfwUsueL4ULeWY/tULVHfMFopJWtzXUgnBPuS1LBp7/BtmRB3bJ4V/rM1ugjpEv7tKRSKFdEIJK/cjEbQ95zAJMhDK9E9SZy1zrgJ3CojhJLT0mNDCWHFJns8X1btwRTXkclLyfXwRwP1ldShRBwScSaU7x8t+DnLryTA0DR6O17cZRtuaPW1odsIwapEXslu6e4Kuuc1rpCYl05mt0phHq6MNJlisIDXcnqHnhkvvobcOxNAGZEfOMfpV/wJoiHaPekSqvfHL+WEEiEJQ56IOE3UD7RfmbkxbJ22lv4i1wHgDS2m7F2Fmc2j+M3Zgm8VUBM+XylP7Jb72qAKfRMVmHf3mRf+wdDGANa6foUv4HfOs6cJK48x1/hVusup+BdIifrI=
  app: evening-hollows-59256
  on:
    repo: navkelley/baby-steps
